### ISSUE TITLE
Need a math command

### ISSUE THREAD

**Issue by saiTama-max** [fisher60/Friendo_Bot#112]
a math command with small math functions, also i will be working on this right away

**Comment by fisher60** [comment]
Sounds good, just do not use eval()

**Comment by aish0007** [comment]
can u assign this to me

**Comment by fisher60** [comment]
@aish0007 sorry, I meant to assign saitama, this issue is being worked on.

**Comment by Vyvy-vi** [comment]
Is this issue still going on?
I have a suggestion... we can add better functionality if we just use wolfram's api

**Comment by Xithrius** [comment]
If this issue is still relevant, using the Wolfram Alpha API would be much easier than programming an entire DSL or a function with a bunch of if statements.

**Comment by saiTama-max** [comment]
i will look into the wolfram api for this

**Comment by saiTama-max** [comment]
i think i can close this issue now, i already did a pr for the wolfram api

**Comment by Xithrius** [comment]
This issue will be closed automatically if you include "Closes #112" within your PR comment.

**Comment by saiTama-max** [comment]
oooh ok

**Comment by Xithrius** [comment]
@saiTama-max I was wrong. I think this feature is only for the Python Discord repositories. If this doesn't close, feel free to close it on your own.

**Comment by saiTama-max** [comment]
yeah lol
