### ISSUE TITLE
Remove blocking I/O

### ISSUE THREAD

**Issue by decorator-factory** [fisher60/Friendo_Bot#171]
Interacting with the filesystem (with `open`) and the terminal/filesystem (with logging) is done with blocking I/O, which will stop the event loop for their entire duration, undermining all the benefits of asynchronous I/O. Logging might be fine, but filesystem interactions should be done either with a separate thread that reads from a queue, or with `aiofiles` (which does a similar thing).

**Comment by ForbiddenKJ** [comment]
I'll be doing it.
