### ISSUE TITLE
reminder should respond with embed

### ISSUE THREAD

**Issue by fisher60** [fisher60/Friendo_Bot#179]
This is a well known bug/issue that we (I) should have seen coming. The reminder should return an embed as it causes the bot to reply with a raw text input, very dangerous and breaking.

**Comment by GDWR** [comment]
Claimed

**Comment by GDWR** [comment]
using https://discordpy.readthedocs.io/en/latest/ext/commands/api.html?highlight=bot#discord.ext.commands.Bot.allowed_mentions 
to config the mentions across the entire bot

**Comment by GDWR** [comment]
@fisher60 Close this?
