### ISSUE TITLE
Set up error logging

### ISSUE THREAD

**Issue by fisher60** [fisher60/Friendo_Bot#31]
Logs should be sent to a file, use [this reference](https://discordpy.readthedocs.io/en/latest/logging.html) for logging info

**Comment by JacobLJones2011** [comment]
Hiya, it may take me a little while since this would be my first crack at helping on an open source project and my kids are home for school. I am confident that I can get this done, would you mind if I took a swing?

**Comment by fisher60** [comment]
> Hiya, it may take me a little while since this would be my first crack at helping on an open source project and my kids are home for school. I am confident that I can get this done, would you mind if I took a swing?

Of course! any help is greatly appreciated. Feel free to let me know if you have any questions at all.

**Comment by fisher60** [comment]
one more thing: we are working on our documentation, I am not sure if this is explicit anywhere, but our most up to date branch is develop. You must do your work from develop on your fork, do not try to create a PR to master. Just a heads up. Thank you very much.

**Comment by dustin-py** [comment]
I'd like to help out, heads up this is my firs hacktoberfest so bare with me as i learn.

**Comment by fisher60** [comment]
@dustin-py it is all yours, let me know if you have any questions.

**Comment by dustin-py** [comment]
Unfortunately I'm gonna have to opt out of this. Bit of more than I could chew, I'm just lost on whats going on, I could get the bot up and running made the file but I'm not sure how to interact with and test what I'm working on.

**Comment by buyalsky** [comment]
Hi @fisher60, I would like to take this issue.

**Comment by JulianK27** [comment]
Hey could you assign me for taking care of the error logging?.

**Comment by fisher60** [comment]
> Hi @fisher60, I would like to take this issue.

It is all yours.
