### ISSUE TITLE
Improve meme command description and brief

### ISSUE THREAD

**Issue by fisher60** [fisher60/Friendo_Bot#40]
This command is confusing and needs better documentation. Need to remove the extra `.` in the description, as well as any other improvements to make this easier.

**Comment by SavagePastaMan** [comment]
I am new to open source and I would like to contribute.

**Comment by fisher60** [comment]
I assigned this to you. Feel free to comment or use discord for questions. 

This command is basically too confusing for newcomers. It needs a better description that does not require a thorough explanation. Feel free to also modify the command if you also think it will make it easier to use.
