### ISSUE TITLE
Custom help response

### ISSUE THREAD

**Issue by fisher60** [fisher60/Friendo_Bot#82]
Create a custom help command/help output for the bot. The embed should be cleaner than the default and color coded.

**Comment by Aravindha1234u** [comment]
Can you assign this to me I would love to work

**Comment by Aravindha1234u** [comment]
![image](https://user-images.githubusercontent.com/52521300/94890658-77219c00-049d-11eb-9224-b8eb61451a45.png)
@fisher60 Can you check this. So that I can create a PR

**Comment by fisher60** [comment]
Oh wow you work fast, haha. That looks awesome.

**Comment by Aravindha1234u** [comment]
What else should be Added. Any requirements?

**Comment by fisher60** [comment]
Realistically the goal for this issue was just to get something that was not painful to look at. You went above and beyond. Feel free to add anything you think is useful for the command.

**Comment by Aravindha1234u** [comment]
Yah exactly, I taught this is looks clean and neat. I just want to confirm that I didn't miss any command of the bot. So that I can PR for a check and then can be Merged

**Comment by fisher60** [comment]
Pretty sure that is all of them, go ahead and open a PR.

**Comment by Aravindha1234u** [comment]
I have Created a PR. have a look and approve it.
