### ISSUE TITLE
Music Search API 

### ISSUE THREAD

**Issue by mcurranseijo** [fisher60/Friendo_Bot#93]
Has someone begun work on a music search command? I could try starting something like that if no one has yet. Looking around it seems like I could do some decent stuff with the [iTunes API](https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/iTuneSearchAPI/SearchExamples.html#//apple_ref/doc/uid/TP40017632-CH6-SW1)

**Comment by fisher60** [comment]
I believe this is a unique issue. Is this a feature to search for a specific song, album, or artist?

**Comment by mcurranseijo** [comment]
Yep that'll be the goal, put all the needed info (or info I can get) in a nice embed with an image of the album for songs and albums as well, I'll get to work on that and post updates as it goes

**Comment by Xithrius** [comment]
I'd like to see this feature implimented. Are you still interested, @mcurranseijo?

**Comment by mcurranseijo** [comment]
Yes I am it's currently almost finished should be done soon,

**Comment by Xithrius** [comment]
Alright cool. Good luck!
