### ISSUE TITLE
Allow enabling and disabling cogs in settings.py

### ISSUE THREAD

**Issue by fisher60** [fisher60/Friendo_Bot#94]
In order to make the project more accessible to developers, we should allow the disabling of api key dependent cogs in settings.py. We can include commands to disable each cog when running the bot as well. This will allow a user to work on an isolated part of the bot without needing to worry about breaking anything that depends on an account for an api.

An example would be to run `python -m bot --no-api` or something similar.

**Comment by Sid200026** [comment]
I can take up this issue
