### ISSUE TITLE
Automate custom help command

### ISSUE THREAD

**Issue by fisher60** [fisher60/Friendo_Bot#95]
We now have a custom help command, but it depends on being hard-coded. Changes should be made to allow the custom help command to behave similarly to the built-in help command. It should display the command Cog name, commands available, and the brief.

The help command should also provide the description of the command when entering something like `.help hello`

**Comment by ptrstr** [comment]
Could you assign me to it?

**Comment by fisher60** [comment]
Yessir.

**Comment by ptrstr** [comment]
There's a lot of commands and not every command fits in a single field of the body on the embed. (That's with the command followed by the brief message) My current solution is 1 embed per cog but it might be spammy. Is that ok for you? Alternatively, I could try cropping out the contents of the command or using 1 embed with reactions to move through sections. Or to make it less spammy another method be to list all cogs when running `.help` and then specifying a cog you want help on so like `.help Events` for example. Thanks!

**Comment by ptrstr** [comment]
See PR #103 for a fix on this issue
