### ISSUE TITLE
Help command mobile too small

### ISSUE THREAD

**Issue by fisher60** [fisher60/Friendo_Bot#97]
Using the embed makes the help command unreadable on mobile.

**Comment by Vortex2wenty** [comment]
Claim

**Comment by fisher60** [comment]
It is all yours, thank you. I believe the culprit may be the included image? Not sure. I have seen other help embeds work find on mobile.

**Comment by fisher60** [comment]
This was vaguely addressed in the recent help command changes. If you still wish to improve it, you are free to. I did a very lazy change to make it work for now. Let me know if you still like to attempt to improve this. There are plenty of other issues here to help with if not.
